export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export type ActionType = 'SIGNIN_REQUEST' | 'SIGNIN_SUCCESS' | 'SIGNIN_FAIL';
